### ISSUE TITLE
Roadmap: Text search tools

### ISSUE THREAD

**Issue by bryanwhiting** [GospelAnalysis/searchthescriptures#1]
Given a block of text (set of scriptures, a talk)

- [ ] longest repeated N-grams
- [ ] Word cloud of n-grams (or box plot)
- [ ] Topics (topic modeling)
- [ ] Uniqueness (what's unique about this text relative to other texts?)
- [ ]
